### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by marlonemmerich** [alexrobaina/frontend_petsLove#115]
Hey, @alexrobaina! How are you?
I'm still need 2 PR to complete the hacktoberfest chalenge. Can you  contribute with some think, for example, like a dependencies upgrade.
If you aceept, i will create a PR.
Thanks!

**Comment by marlonemmerich** [comment]
If you agree, i create a [PR](https://github.com/alexrobaina/frontend_petsLove/pull/116)
I dont upgraded node-fetch cause the v3 is in beta =\
![image](https://user-images.githubusercontent.com/52637919/97790556-3e620900-1ba8-11eb-8e33-b6ef87bf4b01.png)
If you need any help, i will need one more PR (if you aceept this hahah)
Thanks again!

**Comment by alexrobaina** [comment]
Hi @marlonemmerich, thanks for this contribution but in this moment I making very big upgraded for mobx, react and all dependence.

For this reason I'm not merge this PR. Sorry

Thanks you! 😄
