### ISSUE TITLE
Add button for Edit pets

### ISSUE THREAD

**Issue by alexrobaina** [alexrobaina/frontend_petsLove#164]
Create a button for Edit pets in PetCard. 

- [] Create button - please use the BaseButton and when the user clicks to redirect editPet/petId
Like this: 
<img width="415" alt="Screen Shot 2022-10-02 at 10 16 57 AM" src="https://user-images.githubusercontent.com/30770802/193456068-d64743c5-9864-4cfe-be3d-4881433769a2.png">

- [] The button needs to hide when the user it's not the creator pet. Please add prop disabledActions type boolean in PetCard and check that with useSession from nextjs

**Comment by najeebkp** [comment]
Hi @alexrobaina ,
I would like to work on this. Please assign me this issue.

**Comment by alexrobaina** [comment]
Great! Thank you @najeebkp
