### ISSUE TITLE
Create Profile pet

### ISSUE THREAD

**Issue by alexrobaina** [alexrobaina/frontend_petsLove#175]
https://www.figma.com/file/MK1mSVutBHbVXEo4VyfzVf/Pets-love-system-design?type=design&node-id=3128%3A20436&mode=design&t=oHFPr01a3bDbZSyh-1

**Comment by ivanosquis10** [comment]
Hello friend, the idea would be to create the profile page of the puppy as it is in the figma, right?

**Comment by alexrobaina** [comment]
Hi @ivanosquis10 yes of course. 
Let me check the firma and complete the issue with more information.

**Comment by noslenPantaleon** [comment]
Hi I am here!

**Comment by ivanosquis10** [comment]
ohhh okay <333

**Comment by robo311** [comment]
Is it still worked on? I would like to get assigned this issue

**Comment by noslenPantaleon** [comment]
hi!,  I am working on this, is almost done!..
