### ISSUE TITLE
Create LinkedIconText Component

### ISSUE THREAD

**Issue by alexrobaina** [alexrobaina/frontend_petsLove#178]
To enhance UI modularization and reusability, there's a need to create a small, reusable component that will display an address or any other text along with an icon. The text needs to be a clickable link that redirects to a provided URL in a new tab. This component will receive the following props:

Icon
URL
Text

### This is an example: 
<img width="293" alt="Screen Shot 2023-09-22 at 08 09 53" src="https://github.com/alexrobaina/frontend_petsLove/assets/30770802/7813c5e6-4238-4e06-b0b0-6782dad329b9">

- [ ]  Create a new functional component with a chosen name from the proposed component names or any suitable name.
- [ ] The component should receive props for Icon, URL, and Text. 
- [ ] The Text should be a clickable link that opens the provided URL in a new tab.
- [ ] The component should be styled appropriately to match the existing UI.
- [ ] Write unit tests to ensure the component behaves as expected.
- [ ] Update documentation with the new component usage. (Check the route http://localhost:3000/ui)

### How to Test
- Use the new component in a view with different sets of prop values.
- Ensure the component renders correctly and the link opens in a new tab.
- Ensure the unit tests pass.

**Comment by ishaanparlikar** [comment]
Hey @alexrobaina 
I can pick this up.

**Comment by alexrobaina** [comment]
Hi @ishaanparlikar. Yes, of course, I'm going to assign you.

**Comment by ishaanparlikar** [comment]
Thanks @alexrobaina 
I will start working on it.

**Comment by Shubhcoder** [comment]
If he is not working, then I can work on it (since I think it is needed as a part of #209).

**Comment by alexrobaina** [comment]
Yes, you are right. You need this component for Profile User. 
Thanks.

**Comment by Shubhcoder** [comment]
Hi, @alexrobaina 

Does the icon props needs to be a component (imported from icons in asset folder) or it is just an url placeholder?

Or shall I give the option of both? (i.e., both icon url and icon component will be accepted)
