### ISSUE TITLE
Create SwiperGallery Component

### ISSUE THREAD

**Issue by alexrobaina** [alexrobaina/frontend_petsLove#180]
To improve the user interface and the user experience on our platform, there is a requirement to develop a reusable gallery component using SwiperJS. This component should provide a seamless and responsive way to view a collection of images.

### This component should receive the following props:

images: An array of image URLs to be displayed in the gallery.
thumbs: An array of thumbnail image URLs corresponding to the images in the gallery.

### Acceptance Criteria

- [x]  Create a new functional component named SwiperGallery.
- [x]  The component should receive images and thumbs as props.
- [x]  The gallery should display the main images and a thumbnail navigation.
- [x]  Use SwiperJS to implement the gallery slider functionality.
- [x]  The component should be responsive and work smoothly on different screen sizes.
- [ ]  Write unit tests to verify the component's functionality.
- [ ]  Update the component documentation with usage examples and prop descriptions.

### How to Test
Include the SwiperGallery component in a view with different sets of images and thumbs.
Verify that the gallery displays correctly and is responsive to different screen sizes.
Verify that the thumbnail navigation works correctly.
Ensure that the unit tests cover all component functionalities and they pass.

**Comment by shivaram19** [comment]
could you please assign me this task @alexrobaina ?
Thank you !
