### ISSUE TITLE
Create BaseTextArea Component

### ISSUE THREAD

**Issue by alexrobaina** [alexrobaina/frontend_petsLove#181]
To standardize and make the text area input more reusable across our application, there is a requirement to create a new component named BaseTextArea. This component will be developed with reference to the existing BaseButton component located in src/components/BaseButton.

### Acceptance Criteria

- [ ] Develop a functional component named BaseTextArea.
- [ ]  The component should accept the following props:
- [ ] value: The value inside the textarea.
- [ ] handleChange: The function to be called when the value of the textarea changes.
- [ ] classname: The className to be applied to the textarea for styling.
- [ ] height: The height of the textarea.
- [ ] textHelper: Helper text to be displayed below the textarea.
- [ ] textError: Error text to be displayed if there is an error.
- [ ] The component should be well-styled, keeping consistency with the existing UI 

### How to Test
- Integrate the component in different parts of the application with varying prop values.
- Check whether all the props are working as expected.
- Check whether the handleChange is triggered on value change.
- Ensure that the unit tests cover all possible use cases and edge cases and they pass.

**Comment by usrj03l** [comment]
hi i would love to contribute, the readme says refer to the contributing file but i dont see any.

**Comment by alexrobaina** [comment]
I @usrj03l, I'm sorry for that. You are right. I will go to fix that. Thanks.

You must make a fork and create a PR to collaborate on this issue.

**Comment by usrj03l** [comment]
I need the instructions on how to setup the project

**Comment by alexrobaina** [comment]
Hi @usrj03l I updated the contributing file. You can follow this instruction. 
Please if you have any problem you can ask. 

Thanks

**Comment by usrj03l** [comment]
Thanks 👍

**Comment by usrj03l** [comment]
Should i install the backend as well.

**Comment by alexrobaina** [comment]
Hi @usrj03l! It is not necessary. You can develop and check the component on the page LoginPage.tsx
Only to check if your component is fine. 

The objective of this issue is to create this small component.
