### ISSUE TITLE
Create BasePhoneInput Component using react-phone-input-2

### ISSUE THREAD

**Issue by alexrobaina** [alexrobaina/frontend_petsLove#182]
To streamline the user interface and maintain a consistent look and feel across the application, we need to create a new reusable component, BasePhoneInput, for phone number input. This component will leverage the react-phone-input-2 library and should adhere to the styling of the existing BaseInput component.

### Acceptance Criteria

- [x]  Develop a functional component named BasePhoneInput.
- [x]  Use react-phone-input-2 as the foundational library for the component.
- [x]  The component should have styling consistent with BaseInput.
- [x]  Ensure proper functionality and error handling of the phone input.
- [ ]  Test the component to ensure that it meets the requirements and behaves as expected.

How to Test
- Use the component in various parts of the application.
- Ensure that the component behaves as expected and handles errors gracefully.
- Check the styling to confirm it aligns with BaseInput.
- Run the unit tests to validate the component's functionality.

**Comment by SyedaMahamFahim** [comment]
Hello, i am interested in working on this task for the upcoming hacktoberfest.

**Comment by alexrobaina** [comment]
Hi @SyedaMahamFahim. Awesome! 

Well, this issue needs to develop a test because the component was created and finished.
You can find the component in this path src/components/BasePhoneInput.

Do you want to take the test?
