### ISSUE TITLE
Tests for App.tsx file is failing with errors

### ISSUE THREAD

**Issue by Shubhcoder** [alexrobaina/frontend_petsLove#184]
**Steps to produce error**

1. From root folder run --> **`yarn test src/tests/App.spec.tsx`**

2. You will see it failing with errors in `GoogleAutocomplete` component file.

**Comment by alexrobaina** [comment]
Hi @Shubhcoder. I'd made a mistake and merged before October. I'm sorry.

**Comment by Shubhcoder** [comment]
Hi, @alexrobaina. No worries at all, my ultimate aim is to make contributions to this repo. So, as long as I am able to make good PR's (that's what matters to me).
