### ISSUE TITLE
Create ErrorBoundary Component using ViteJS, React, and TailwindCSS

### ISSUE THREAD

**Issue by alexrobaina** [alexrobaina/frontend_petsLove#186]
To enhance user experience and handle errors gracefully, there is a need to implement a custom ErrorBoundary component in our ViteJS, React, and TailwindCSS application. This component will capture JavaScript errors anywhere in a component tree and log those errors, and display a fallback UI instead of crashing the component tree.

## Acceptance Criteria

- [ ]  Develop a class component named ErrorBoundary that utilizes the lifecycle method componentDidCatch to capture errors.
- [ ]  Display a user-friendly error message and hint for developers when an error is captured.
- [ ]  Style the fallback UI using TailwindCSS to maintain consistency with the rest of the application.
- [ ]  Test the component with different types of errors to ensure it captures and displays

**Comment by Shubhcoder** [comment]
Hi, @alexrobaina 

Can I work on this one?

**Comment by Shubhcoder** [comment]
Can you please put labels in this issue? (specially the hacktoberfest one :sweat_smile: )

**Comment by Shubhcoder** [comment]
Hi, @alexrobaina 

What error message should be displayed in the fallback UI?

Currently, I am using
```
Oops!
Something went wrong...
Don't worry you can safely go back home
```

Here, clicking on `home` word will take user back to homepage.

**Comment by alexrobaina** [comment]
Hi @Shubhcoder, Thanks, excellent! 
This message sounds excellent. But Don't we have access to the explicit error? 

For example, in the next screenshot, we can see the suggestion from Vitejs to create the ErrorBoundary and the text "slideVariants is not defined": 
<img width="606" alt="Screen Shot 2023-10-04 at 13 42 43" src="https://github.com/alexrobaina/frontend_petsLove/assets/30770802/7b8e9166-b629-48c5-bd2f-640973fc3ace">

**Comment by Shubhcoder** [comment]
Hey, okay.

Actually I misunderstood the requirements(slightly), that technical error message should be logged inside console only. And, for user we will have a generic non-tech message.

We can have that error message displayed on page. And, the below stack-trace-back log in the console i.e, the error page will show (for above scenario, with the component traceback being logged inside console)
```
Oops!
Something went wrong...
Error: slideVariants is not defined
```
Or you want some different error message template? Also, shall I keep the home link message (`Don't worry you can safely go back home`) too?

**Comment by Shubhcoder** [comment]
Like this
![errorBoundary](https://github.com/alexrobaina/frontend_petsLove/assets/46351104/d203d842-5e5a-469b-be75-8d64eb6fec37)

**Comment by Shubhcoder** [comment]
Hey,

So, shall I go with the screenshot I sent you from my current implementation?

**Comment by alexrobaina** [comment]
Yea! It's okay for me. Let's do it!
