### ISSUE TITLE
Error when run test. import.meta.env...

### ISSUE THREAD

**Issue by alexrobaina** [alexrobaina/frontend_petsLove#190]
![Screen Shot 2023-09-27 at 15 17 38](https://github.com/alexrobaina/frontend_petsLove/assets/30770802/7e26c92a-1eea-4675-b8a8-2ea334c62812)

**Comment by Shubhcoder** [comment]
Hi, @alexrobaina. Can I take this one?

**Comment by alexrobaina** [comment]
Hi @Shubhcoder! Yeah please.

Thanks you!
