### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by alexrobaina** [alexrobaina/frontend_petsLove#205]
The goal of this issue is to create a step-by-step process to run the project in the local. 

It's important to know that we use node v18

**Comment by DiguyaDeveloper** [comment]
Could you sign this issue for me, please?

**Comment by Shubham23011** [comment]
Hey @alexrobaina I have understood your issue, so can you assign this issue to me.

**Comment by alexrobaina** [comment]
Hi @DiguyaDeveloper, Yes, of course. If you have any questions, please tell me
Thank you.

**Comment by alexrobaina** [comment]
Hi @Shubham23011 I'm sorry. I assigned this issue to DiguyaDeveloper.

**Comment by Shubham23011** [comment]
okk no problem,
