### ISSUE TITLE
Create Profile user

### ISSUE THREAD

**Issue by alexrobaina** [alexrobaina/frontend_petsLove#209]
This issue aims to Create a profile user.  
In Pet's Love, we have four kinds of users ADOPTER, VET, VOLUNTEER and SHELTER. This user page needs to work for all users. 
It cannot be easy because the data between users' roles are similar. 

https://www.figma.com/file/MK1mSVutBHbVXEo4VyfzVf/Pets-love-system-design?type=design&node-id=3128-20356&mode=design&t=xW1XQdtwFR1AWDUu-0

Please use the component in Pet Profile to build a user profile. In Figma, you can check the information that the profile needs to show. frontend_petsLove/src/pages/ProfilePetPage

**Comment by Shubhcoder** [comment]
Hi, @alexrobaina 

Can I work on it?

**Comment by alexrobaina** [comment]
Hi @Shubhcoder! Yes, please. 😄 

Thanks help to build build this project 🚀

**Comment by Shubhcoder** [comment]
Hey, thank you!

**Comment by Shubhcoder** [comment]
Hi, @alexrobaina 

I have few doubts/questions in this:-
1. I think few components required in this are not ready yet (eg., card with picture of pet with brief info, etc). If I am not wrong here, then I will go ahead and start finishing such parts.
2. Any structure you have in mind regarding the way this Profile will receive inputs to be displayed? (I think this component is going to receive data from backend directly)

Please, correct me if I am wrong in anywhere and looking forward to your feedback.

**Comment by alexrobaina** [comment]
Hi @Shubhcoder, sorry for answering you later.

If you make a pull from the main, you check the pet profile and take it for references.

The header of the user profile can be like a pet profile, and we need to show all social media buttons like Instagram, Facebook, and WhatsApp on the top of the page (The next week, I can send you an example)
![Screen Shot 2023-11-02 at 20 45 36](https://github.com/alexrobaina/frontend_petsLove/assets/30770802/65e2de51-91a5-44a2-b5fc-1f5688d15200)

In the volunteer section, we can use the ContactInfo component. 
![Screen Shot 2023-11-02 at 20 48 51](https://github.com/alexrobaina/frontend_petsLove/assets/30770802/697b2a54-1959-431c-ba60-d06595a66cc2)

Finally, we need to show all pets from the user and add filters like Adopted, cat, dog, female, and male. This part is similar to the dashboard. 
 
![Screen Shot 2023-11-02 at 20 50 54](https://github.com/alexrobaina/frontend_petsLove/assets/30770802/e84a40ef-9e90-4059-88c0-a06d461d7181)
![Screen Shot 2023-11-02 at 20 51 36](https://github.com/alexrobaina/frontend_petsLove/assets/30770802/84e9ebfd-6989-4bde-b212-45a6d9257351)

I need to resolve several issues in the back to provide this data, but you could create a mock.
For the next week, I'm going to prepare an example, and I will open a discord server to talk with the team and community.

**Comment by Shubhcoder** [comment]
Hi, okay. I will wait for the examples and discord link to clear some more of my confusions.

**Comment by alexrobaina** [comment]
Hi @Shubhcoder! I'm creating the Discord server.
https://discord.gg/RFZjYen5   <----- Link to came to the server 😄

Thanks
