### ISSUE TITLE
Change library Phone or resolve bug 

### ISSUE THREAD

**Issue by alexrobaina** [alexrobaina/frontend_petsLove#77]
The purpose of this task is that the input phone show the countries flags and the user select your country
I use this library [https://www.npmjs.com/package/react-phone-input-2](url)

I would try resolve bug first. xD

Please try in this file: FormRegister.jsx

**Comment by NabeelahY** [comment]
Can I try this?

**Comment by alexrobaina** [comment]
Hi @NabeelahY, yes please. 👍

**Comment by NabeelahY** [comment]
Hi @alexrobaina. Just create a PR for the issue

**Comment by alexrobaina** [comment]
Hi @NabeelahY, now work!! Thanks very much
