### ISSUE TITLE
Add Icon in component InputDate

### ISSUE THREAD

**Issue by alexrobaina** [alexrobaina/frontend_petsLove#79]
**The goal of this issue** is add icon inside InputDate.jsx
Like this: 
![Screen Shot 2020-10-05 at 22 21 01](https://user-images.githubusercontent.com/30770802/95148177-10300b80-0759-11eb-82c0-73b0404d867a.png)

This is import icon that I could import in this component:
`import { BiCalendarHeart } from 'react-icons/bi'`

Maybe 20 size will look good but you can try other sizes . This is syntax for use icon: 
`<BiCalendarHeart size={20} />`

**Comment by nghianv-1868** [comment]
you want it all InputDate ?

**Comment by nghianv-1868** [comment]
Or I write you a component and then where you like to add it is up to you.

**Comment by nghianv-1868** [comment]
![Screenshot from 2020-10-06 09-17-55](https://user-images.githubusercontent.com/49506301/95151453-e573a080-07b4-11eb-9769-2526f28f9de2.png)
Hope you like it

**Comment by alexrobaina** [comment]
Hi @nghianv-1868 yes, you can add icon inside component, it doesn't need to be a prop

**Comment by nghianv-1868** [comment]
you want size is px or % ?

**Comment by nghianv-1868** [comment]
![Uploading Screenshot from 2020-10-06 09-17-55.png…]()

I hope you like it

**Comment by alexrobaina** [comment]
For set size only yo need pass the number in the component icon for example <BiCalendarHeart size={20} />

Please can you try size={18}

**Comment by nghianv-1868** [comment]
ok done

**Comment by alexrobaina** [comment]
@nghianv-1868 Sorry if I don't explain it well.
I'm working with react-icons

You would have to import it
import {BiCalendarHeart} from 'react-icons / bi'

and directly use this component
<BiCalendarHeart size = {20} />

**Comment by nghianv-1868** [comment]
So you want me to create a new component, with a new name, can add custom icons and resize as you like?

**Comment by alexrobaina** [comment]
No, I just need to add the icon in the Input Date.jsx component.
You need to import the icon and position it.
It was fine what you did but I need it to be this icon: 
`import {BiCalendarHeart} from 'react-icons / bi'`
`<BiCalendarHeart size = {20} />`

**Comment by nghianv-1868** [comment]
![image](https://user-images.githubusercontent.com/49506301/95157005-1ad2bb00-07c2-11eb-9b4d-5b46ac8b5221.png)

done

**Comment by nghianv-1868** [comment]
https://github.com/alexrobaina/frontend_petsLove/pull/80

**Comment by alexrobaina** [comment]
@nghianv-1868 Thanks very much for your contribution.

**Comment by nghianv-1868** [comment]
![image](https://user-images.githubusercontent.com/49506301/95186193-ebd53d00-07f3-11eb-8d26-10adf82ee7ed.png)

currently the rules of hacktoberfest.digitalocean.com have changed so pull add icon for my imputDate, although you merge but I have not accepted. Could you please add "hacktoberfest-accepted" to my old pull label

**Comment by nghianv-1868** [comment]
![image](https://user-images.githubusercontent.com/49506301/95186319-10c9b000-07f4-11eb-90bb-6b62a4f81025.png)

**Comment by alexrobaina** [comment]
Ok no problem. Now the issue have the label hacktoberfest-accepted
Thanks for advising.
