### ISSUE TITLE
Bug in component <GoogleAutocomplete>

### ISSUE THREAD

**Issue by alexrobaina** [alexrobaina/frontend_petsLove#82]
The goal of the task it is to make the input show the full address when the user select it.
When the user clicks on the address, the input does not autocomplete correctly, but if he does enter, it works.

<img width="912" alt="Screen Shot 2020-10-08 at 01 50 54" src="https://user-images.githubusercontent.com/30770802/95416455-35fc1280-0909-11eb-8037-6f2b91bf3c54.png">

**Comment by logesr** [comment]
I can take this up!

**Comment by chachan** [comment]
I can tackle this

**Comment by alexrobaina** [comment]
Hi @chachan Nice. I'm going to assign you the issue!
Thanks you very much!

**Comment by martinpastore** [comment]
hey @alexrobaina @chachan. I'm sorry I've created a PR to fix this but I've realized that was already assigned. I'm sorry, let me know and I can't drop off my PR

**Comment by alexrobaina** [comment]
Hi @martinpastore I'm going to check your PR. I don't know if @chachan could solve it.
