### ISSUE TITLE
Traducciones  Español a Ingles / Translations Spanish to English 

### ISSUE THREAD

**Issue by alexrobaina** [alexrobaina/frontend_petsLove#91]
**The goal of this issue** is to verify and correct the translations.
In the folder public/locales/en and public/locales/es you can find the files translations.

Specially the translations of the landing page => en/landingpage.json - es/landingpage.json

Please if you find errors in other parts of the site you can send a PR ❤️ 😀

**Comment by alanverdugo** [comment]
Hi @alexrobaina , I can help with this.
Please assign the issue to me. Thanks!

**Comment by alexrobaina** [comment]
Yes, it would be great!
Thanks you very much!
