### ISSUE TITLE
Portuguese translations

### ISSUE THREAD

**Issue by alexrobaina** [alexrobaina/frontend_petsLove#95]
The objective of this issue is to translate to portuguese

The translations are in the folder public/locales
To add portuguese you need create folder called pt and copy&paste the same files that are in any other language.

After this can change the files .json
Add list of the all files need change: 

- [x] common.json
- [x] containerPetsCards.json
- [x] createPet.json
- [x] dashboard.json
- [x] editPet.json
- [x] editUser.json
- [x] forgotPassword.json
- [x] googleMapCard.json
- [x] home.json
- [ ] landingPage.json
- [ ] medicalInformationCat.json
- [ ] medicalInformationDog.json
- [ ] navbar.json
- [ ] petsFilterForm.json
- [ ] profilePets.json
- [ ] resetPassword.json
- [ ] searchProtectionist.json
- [ ] searchVolunteers.json
- [ ] signIn.json
- [ ] socialMediaButtons.json
- [ ] whatsappMessage.json

**Comment by marlonemmerich** [comment]
Maybe I can help if you want!

**Comment by alexrobaina** [comment]
Hi @marlonemmerich sure. 😃
I update the task because @marlonemmerich made it a couple with modified files.
This way do not open conflicts with files. 

Thank you! 😃

**Comment by marlonemmerich** [comment]
Perfect! I will not include unchecked files, right?
In future, if you want portuguese translation for this files, just tell me. Okay?
I'm starting to work on this
Cya!

**Comment by alexrobaina** [comment]
Sorry if I explained wrong.
Made the files that are not marked. 😃
If the other collaborator does not respond in a few days I'm going to ask you for help

Thank you! 😃

**Comment by marlonemmerich** [comment]
Hi!
I've created a new [PR](https://github.com/alexrobaina/frontend_petsLove/pull/108) (108)
If you have any problem with this, just tell me!
Cya!

**Comment by alexrobaina** [comment]
Hi @marlonemmerich! 
I'm going to merge this PR 😃!

I'm also going to merge el PR of the other collaborator!
After that would you like to check the others files json in Portuguese? 

Thank you! 😃

**Comment by marlonemmerich** [comment]
Sure! I put some observations on another PR, ok?

**Comment by alexrobaina** [comment]
@marlonemmerich can I ask you something else? 😃
Could you translate the other missing files to PT-BR in a new PR?

Thank you very much!

**Comment by marlonemmerich** [comment]
Sure! I'm working on this here!

**Comment by alexrobaina** [comment]
Oh! please, you can rename the folder because maybe I generate conflicts

**Comment by marlonemmerich** [comment]
Hello, again!
I've created a new [PR](https://github.com/alexrobaina/frontend_petsLove/pull/111) with the changes
Can you check, please?
If you have any questions, just ask me!
Cya!

**Comment by alexrobaina** [comment]
Hi @marlonemmerich I checking the pr at the moment. 😃
